version: '3.8'
services:
  database:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./volumes/data:/var/lib/postgresql/data
    ports:
      - "${DOCKER_POSTGRES_PORT}:5432"
    networks:
      - unix-commands
    environment:
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}

networks:
  unix-commands:
